apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot-chart.fullname" . }}
  labels:
    app: {{ include "springboot-chart.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "springboot-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "springboot-chart.name" . }}
    spec:
      containers:
        - name: springboot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
